---
title: "Boxplot_deforest"
output: html_document
---

```{r }

if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plot "
}

```

## Library

```{r }

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(maps)
library(ggplot2)
library(sp)
library(rgdal)
library(raster)
library(ggmap)
library(sf)
library(viridis)

```

## LOADING & MERGING files

```{r }

year_i = 1985
year_f = 2019

df_lsm_i <- list()
df_lsm_f <- list()

for (i in 1:200){

    WD.tmp = list.files(path=dir_data, pattern = paste0("Basin_",i,"_"), full.names = TRUE)

    df_lsm_i[[i]] <- get(load(file=file.path(WD.tmp, paste0(year_i, "_mapbiomas_lsm",i,".RData")))) %>% mutate(annee=year_i) # 3 = natural forest (forest/savanna/mangrove)
    df_lsm_f[[i]] <- get(load(file=file.path(WD.tmp, paste0(year_f, "_mapbiomas_lsm",i,".RData")))) %>% mutate(annee=year_f) # 3 = natural forest (forest/savanna/mangrove)

}


df_lsm_i_bind <- do.call("rbind",df_lsm_i)
df_lsm_f_bind <- do.call("rbind",df_lsm_f)



```

## BUILDING table of values of deforestation

We compute % of lost forest, for the two main agriculture types: pasture or crops

```{r }

list_deforest <- list()

j=0

for (i in 1:200){
  
  perc_past <- (df_lsm_f_bind %>% filter(ID==i, class==15, metric=='pland'))$value
  perc_crop <- (df_lsm_f_bind %>% filter(ID==i, class==41, metric=='pland'))$value ### attention !!
  
  if(is_empty(perc_past)){perc_past=0}
  if(is_empty(perc_crop)){perc_crop=0}
  
  if(perc_past>=0.5){
    j=j+1
    foret_i <- (df_lsm_i_bind %>% filter(ID==i, class==3, metric=='pland'))$value
    foret_f <- (df_lsm_f_bind %>% filter(ID==i, class==3, metric=='pland'))$value
    foret_loss <- foret_i-foret_f
    list_deforest[[j]] <- df_lsm_f_bind %>% filter(ID==i, class==3, metric=='pland') %>% mutate(value=replace(value, value=foret_loss))%>% mutate(maj='past')
    }
  
  if(perc_crop>=0.5){
    j=j+1
    foret_i <- (df_lsm_i_bind %>% filter(ID==i, class==3, metric=='pland'))$value
    foret_f <- (df_lsm_f_bind %>% filter(ID==i, class==3, metric=='pland'))$value
    foret_loss <- foret_i-foret_f
    list_deforest[[j]] <- df_lsm_f_bind %>% filter(ID==i, class==3, metric=='pland') %>% mutate(value=replace(value, value=foret_loss)) %>% mutate(maj='crop')
  }
  
}


df_deforest <- do.call("rbind",list_deforest) %>% mutate(annee=paste0(year_i,"_", year_f))

dim(df_deforest)

```

## BOXPLOTTING

We compute boxplots of % of lost forest, for the two main agriculture types: pasture or crops

```{r }


ggplot(df_deforest) + 
  geom_boxplot(aes(x=factor(maj),y=foret_loss, group=maj, fill=factor(maj)), show.legend = FALSE, alpha=0.2) +
  scale_y_continuous()+
  labs(title = paste0(" % deforested per hydrobasin ", year_i, year_f), x="% deforested", y="")+ 
  theme_bw()+
  theme(axis.text.x = element_text(size = 12), axis.title.x = element_text(size = 10, vjust = 1.5, hjust=1),
        axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 10, angle = 0, vjust=1.05),
        plot.title = element_text(size = 10, face = "bold", hjust=0.5))




```
