---
title: "Boxplot Riparian land use"
output: html_document
---

```{r }

if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plot "
}

```

## Library

```{r }

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(maps)
library(ggplot2)
library(sp)
library(rgdal)
library(raster)
library(ggmap)
library(sf)
library(viridis)

```

## PARAMETERS

```{r }

# foret = 3, savanna = 4, pasture = 15, soybean = 39, other temp.crops = 41, per.crops = 36

time_laps <- c(1985:2019)
year=2019
y <- which(time_laps==year)
lu.code = 3
lu.name = "forest"
tampon = 100

basin_select <- st_read(file.path(dir_data, "hydroshed", "basin_select.shp"))

```

## LOADING & MERGING files


```{r }

list_lsm <- list()
list_buf <- list()
j=0
for (basin_id in basin_select$HYBAS_ID){
j =j+1
    WD.tmp = list.files(path=dir_data, pattern = paste0("_",basin_id), full.names = TRUE)[1]
    
    list_buf[[j]] <- get(load(file=file.path(WD.tmp, paste0("mapbiomas_lsm_buf",tampon,"_",basin_id,".RData"))))
    
    if(list_buf[[j]]=="nonascente"){
      list_buf[[j]] <- NA
      list_lsm[[j]] <- NA
    }
    
    else {list_lsm[[j]] <- get(load(file=file.path(WD.tmp, paste0("mapbiomas_lsm_",basin_id,".RData")))) %>% mutate(annee=year, ID=basin_id)
    list_buf[[j]] <- list_buf[[j]] %>% dplyr::select(-ID,-id) %>% mutate(annee=year, ID=basin_id) }
    
    

}

df_lsm_rv <- do.call("rbind",list_lsm) %>% filter(layer==y)
df_buf <- do.call("rbind",list_buf) %>% filter(layer==y)
dim(df_buf)
dim(df_lsm_rv)

```

## BUILDING table of values of deforestation

We compute % of lost forest, for the two main agriculture types: pasture or crops

```{r }

list_forest <- list()

j=0

for (basin_id in basin_select$HYBAS_ID){
  
  perc_past <- (df_lsm_rv %>% filter(ID==basin_id, class==15, metric=='pland'))$value
  perc_crop <- (df_lsm_rv %>% filter(ID==basin_id, class==39, metric=='pland'))$value ### attention !!
  
  if(is_empty(perc_past)){perc_past=0}
  if(is_empty(perc_crop)){perc_crop=0}
  
  if(perc_past>=50){
    j=j+1
    list_forest[[j]] <- df_buf %>% filter(ID==basin_id, class == 3, metric=='pland') %>% mutate(maj='pasture')
    }
  
  if(perc_crop>=50){
    j=j+1
    list_forest[[j]] <- df_buf %>% filter(ID==basin_id, class == 3, metric=='pland') %>% mutate(maj='soybean')
  }
  
}


df_rv <- do.call("rbind",list_forest) 
dim(df_rv)

```

## Statistical tests

```{r }

df_crop_rv <- df_rv %>% filter(maj=='soybean') %>% dplyr::select(value)
df_past_rv <- df_rv %>% filter(maj=='pasture') %>% dplyr::select(value)

# 1. Normality

shapiro.test(unlist(df_past_rv))

ggplot(df_rv %>% filter(maj=='soybean'))+
  geom_histogram(aes(x=value))

ggplot(df_rv %>% filter(maj=='pasture'))+
  geom_histogram(aes(x=value))

dim(df_crop_rv) # 148 obs
dim(df_past_rv) # 180 obs

# 2. Test Student (moyenne)

t.test(unlist(df_crop_rv), unlist(df_past_rv))

# 2. Test Wilcoxon (distribution)

wilcox.test(unlist(df_crop_rv), unlist(df_past_rv))


```

## BOXPLOTTING

We compute boxplots of % of lost forest, for the two main agriculture types: pasture or crops

```{r }


ggplot(df_rv) + 
  geom_boxplot(aes(x=factor(maj),y=value, group=maj, fill=factor(maj)), show.legend = FALSE, alpha=0.2) +
  scale_y_continuous()+
  labs(title = paste0(" % ", lu.name," per hydrobasin RV ", tampon, "m in ", year), x="", y="%")+ 
  theme_bw()+
  theme(axis.text.x = element_text(size = 12), axis.title.x = element_text(size = 10, vjust = 1.5, hjust=1),
        axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 10, angle = 0, vjust=1.05),
        plot.title = element_text(size = 10, face = "bold", hjust=0.5))

ggsave(file.path(dir_plot, paste0(year, lu.name, tampon,"cropast.buf.boxplot.pdf")), dpi = 300)


```