---
title: "Crop or pasture"
output: html_document
---

We plot pasture percentage vs soybean percentage, at basin level, for each basin.
We build the shapefile of these summarized data as well.

```{r }

if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plot"
}

```

## Library

```{r }

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(maps)
library(ggplot2)
library(ggmap)
library(sf)

```

## PARAMETERS

```{r }

# foret = 3, savanna = 4, pasture = 15, soybean = 39, other temp.crops = 41, per.crops = 36

year = 2019

basin_select <- st_read(file.path(dir_data, "hydroshed", "basin_select.shp"))

```

## LOADING & MERGING files


```{r }

list_lsm <- list()

j=0

for (i in basin_select$HYBAS_ID){
    
    j=j+1
    
    WD.tmp = list.files(path=dir_data, pattern = paste0("_",i), full.names = TRUE)[1]

    list_lsm[[j]] <- get(load(file=file.path(WD.tmp, paste0("mapbiomas_lsm_",i,".RData")))) %>% mutate(hybas_id=i) 
 
}

df_lsm <- do.call("rbind",list_lsm) %>% filter(metric=='pland', class == 15|class == 39, layer==35) %>% dplyr::select(metric, hybas_id, class, value)  %>% spread(class, value) %>% dplyr::rename(pasture='15', soy='39') %>% mutate_all(~replace(., is.na(.), 0))

df_lsm %>% filter(pasture>75)

df_lsm %>% filter(soy>75)

```

## PLOTTING


```{r }

ggplot(df_lsm) + 
  geom_point(aes(x=pasture,y=soy), show.legend = FALSE, alpha=0.2) +
  geom_hline(yintercept = 50, col='red')+
  geom_vline(xintercept = 50, col='red')+
  #scale_y_continuous(limits = c(0,10))+ 
  labs(x="% pasture", y="% soybean")+ 
  theme_light()+
  theme(axis.text.x = element_text(size = 12), axis.title.x = element_text(size = 10, vjust = 1.5, hjust=1),
        axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 10, angle = 0, vjust=0.99))


ggsave(file.path(dir_plot, paste0(year,"soy_vs_past.boxplot.pdf")), dpi = 300)

```

## BUILDING SHAPEFILE

```{r }

basin_cropast <- basin_select  


for (i in df_lsm$hybas_id){
  basin_cropast[which(i==basin_cropast$HYBAS_ID),'pasture']<-df_lsm[which(i==df_lsm$hybas_id),]$pasture
  basin_cropast[which(i==basin_cropast$HYBAS_ID),'soy']<-df_lsm[which(i==df_lsm$hybas_id),]$soy
}

st_write(basin_cropast, file.path(dir_data, "hydroshed", "basin_cropast.shp"), delete_layer = TRUE)

```





