---
title: "Landscape metrics"
output: html_document
---

## Directories

```{r }

if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plot"
}

```

## Library

```{r }

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(foreach)
library(parallel)
library(doParallel)
library(maps)
library(landscapemetrics)
library(sp)
library(rgdal)
library(raster)
library(sf)
library(terra)

```

## Parameters

```{r }

year <- 2019
time_span <- c(1985:2019)
y <- which(year==time_span)
tampon <- 500 #100, 250, 500

```

## Computing metrics on whole basin

```{r }

tictoc::tic()

  no_cores <- detectCores()
  cl <- makeCluster(no_cores) # setting up number of cores
  registerDoParallel(cl) # parallelizing on them
  
  foreach(i=c(1:2031), .packages=c('landscapemetrics', 'terra', 'raster')) %dopar%  { 


  # directory
  WD.tmp = list.files(path=dir_data, pattern = paste0("Basin_",i,"_"), full.names = TRUE)
  
  # loading landuse data
  mapbiomas <- rast(file.path(WD.tmp, paste0("mapbiomas_",i, ".tif")))
  
  #computing landscape metrics at basin scale (MapBiomas)
  mapbiomas.basin.lsm = calculate_lsm(mapbiomas,level="class",metric = c("ca","pland","np"),directions =8)
  
  mapbiomas.basin.df = as.data.frame(mapbiomas.basin.lsm)
  
  mapbiomas.basin.df$ID = i
  
  save(mapbiomas.basin.df, file = file.path(WD.tmp, paste0("mapbiomas_lsm",i,".RData")))

}

  stopCluster(cl)
tictoc::toc()



```

## Computing metrics on riparian vegetation

We assess 3 buffer size: 100, 250, 500 meters

```{r }

tictoc::tic()

  no_cores <- detectCores()
  cl <- makeCluster(no_cores/2) # setting up number of cores
  registerDoParallel(cl) # parallelizing on them
  
  foreach(i=c(1:2031), .packages=c('landscapemetrics', 'terra', 'raster', 'sf')) %dopar%  { 


  # directory
  WD.tmp = list.files(path=dir_data, pattern = paste0("Basin_",i,"_"), full.names = TRUE)
  
  # loading landuse data
  mapbiomas <- rast(file.path(WD.tmp, paste0("mapbiomas_",i, ".tif")))
  nascente <- st_read(file.path(WD.tmp, paste0("nascente_",i,".shp"))) 
  
  if(nrow(nascente)>0){
    
    nascente.buf100 = st_buffer(nascente, dist = tampon)
    mapbiomas_buf = terra::mask(mapbiomas,vect(nascente.buf100))
  
    #computing landscape metrics at basin scale (MapBiomas)
    mapbiomas.basin.lsm = calculate_lsm(mapbiomas_buf,level="class",metric = c("ca","pland","np"),directions =8)
    
    mapbiomas.basin.df = as.data.frame(mapbiomas.basin.lsm)
    
    mapbiomas.basin.df$ID = i
  }
  
  else {mapbiomas.basin.df <- "nonascente"}
  
  save(mapbiomas.basin.df, file = file.path(WD.tmp, paste0("mapbiomas_lsm_buf",tampon, "_",i,".RData")))

}

  stopCluster(cl)
tictoc::toc()



```