---
title: "Landscape metrics on MODIS land use"
output: html_document
---

## Directories

```{r }

if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plot"
}

```

## Library

```{r }

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(foreach)
library(parallel)
library(doParallel)
library(maps)
library(landscapemetrics)
library(sp)
library(rgdal)
library(raster)
library(sf)
library(terra)

```

## Parameters

```{r }

year <- 2019
tampon <- 100 #100, 250, 500 reste a faire 250

basin_select <- st_read(file.path(dir_data, "hydroshed", "basin_select.shp"))

```

## Computing metrics on whole basin

```{r }

tictoc::tic()

  no_cores <- detectCores()
  cl <- makeCluster(no_cores) # setting up number of cores
  registerDoParallel(cl) # parallelizing on them
  
  foreach(basin_id=basin_select$HYBAS_ID, .packages=c('landscapemetrics', 'terra', 'raster')) %dopar%  { 

  # directory
  WD.tmp = list.files(path=dir_data, pattern = paste0("_",basin_id), full.names = TRUE)[1]

  # loading landuse data
  modis <- rast(file.path(WD.tmp, paste0("modis_", basin_id, ".tif")))
  
  #computing landscape metrics at basin scale (MapBiomas)
  modis.basin.lsm = calculate_lsm(modis,level="class",metric = c("ca","pland","np"),directions =8)
  
  modis.basin.df = as.data.frame(modis.basin.lsm)
  

  save(modis.basin.df, file = file.path(WD.tmp, paste0("modis_lsm_",basin_id,".RData")))

}

  stopCluster(cl)
tictoc::toc()

```

