---
title: "Sum up modis landscape metrics"
output: html_document
---

```{r }

if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plot"
}

```

## Library

```{r }

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(maps)
library(ggplot2)
library(sp)
library(rgdal)
library(raster)
library(ggmap)
library(sf)
library(viridis)

```

## PARAMETERS

```{r }

# 104 millet cotton, 106 soy millet, 108 soy cotton, 109 soy corn, 

time_laps <- c(2002:2019)
year=2019
y <- which(time_laps==year)

```

## LOADING & MERGING files

We filter and merge into dataframes landscape metrics output

```{r }

basin_select <- st_read(file.path(dir_data, "hydroshed", "basin_select.shp"))

list_modis <- list()

j=0

for (basin_id in basin_select$HYBAS_ID){
  
j =j+1

    WD.tmp = list.files(path=dir_data, pattern = paste0("_",basin_id), full.names = TRUE)[1]

    list_modis[[j]] <- get(load(file=file.path(WD.tmp, paste0("modis_lsm_",basin_id,".RData")))) %>% mutate(annee=year, ID=basin_id)
    
}

df_modis <- do.call("rbind",list_modis) %>% filter(layer==y)

```

## SETTING up table of double culture percentages

It is set up in order to be directly used for boxplotting

```{r }

# whole basin double culture percentages

list_dbcult <- list()
j=0

for (basin_id in basin_select$HYBAS_ID){
  
    j=j+1
    list_dbcult[[j]] <- df_modis %>% filter(ID==basin_id, class == 104|class == 106|class == 108|class == 109, metric=='pland') 

}

df_dbcult <- do.call("rbind",list_dbcult) %>% mutate(annee=year) %>% dplyr::select(-id)

save(df_dbcult, file=file.path(dir_plot, paste0("df_dbcult.RData")))

```


