---
title: "Shapefile of % forests in riparian area"
output: html_document
---

```{r }

if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plot"
}

```

## Library

```{r }

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(maps)
library(ggplot2)
library(sf)

```

## PARAMETERS

```{r }

# foret = 3, savanna = 4, pasture = 15, soybean = 39, other temp.crops = 41, per.crops = 36

time_laps <- c(1985:2019)
year=2019
y <- which(time_laps==year)
tampon = 100

```

## BUILDING SHAPEFILE

```{r }

# Loading selected basins
basin_select <- st_read(file.path(dir_data, "hydroshed", "basin_select.shp"))

# Loading table of riparian forested area
df_rios_foret <- get(load(file=file.path(dir_plot, paste0("df_rios_foret_", tampon, ".RData"))))

# Adding table info to shapefile of basins
basin_db <- basin_select 

for (i in df_rios_foret$ID){
  shp_rios_foret[which(i==shp_rios_foret$HYBAS_ID),'buf.foret']<-df_rios_foret[which(i==df_rios_foret$ID),]$value
}

st_write(shp_rios_foret, file.path(dir_data, "results_shp", paste0("riosbuf_", tampon, "foret.shp")), delete_layer = TRUE)

```